### ISSUE TITLE
Origin OS Version Bypass

### ISSUE THREAD

**Issue by chylex** [chylex/Blog#1]

**Comment by enigmaxg2** [comment]
Does this also work with Windows 8.1? since is a DX11 game, it should right? but I want to be sure before risking my money.

**Comment by chylex** [comment]
It should. If it doesn't, just request a refund of the game.

**Comment by Pic889** [comment]
@enigmaxg2

Running it on Win8.1 with Nvidia GeForce 880M and it works just fine.

**Comment by whitenoise3608** [comment]
Need new fix, version 10.5.66.38849 - 759745

**Comment by chylex** [comment]
Updated.

**Comment by plateau-n** [comment]
This guide works fine for Origin.exe and OriginClientService.exe, but not for the .dll. I was able to download but game won't install on Win7. At Offset 386965 I see 77 fc 8d 77 fc 6a and at 386AEA I see 8d 0c cd 04 20 20 instead of the above. OriginClient.dll version is 10.5.66.38849, maybe I am too stupid for this guide, but could you please check. Thank you.

**Comment by chylex** [comment]
You're looking at the revision for `37936`, not `38849`.

**Comment by plateau-n** [comment]
Any chance to get a fix for 38849? I buy some coffee ...

**Comment by chylex** [comment]
There is a fix for `38849`, either you're on the wrong page or your browser is loading the old revision from cache or something.

**Comment by plateau-n** [comment]
Thank you, could download the game for Win7, but won't install with error 327682:12.

**Comment by jaybuffnfsheat** [comment]
06 July 2020 
I let my guard down. Origin updated itself today. It reports version 10.5.74.41754-762650.

**Comment by ShyPython** [comment]
Need new fix, version 10.5.79.42672 - 763568

**Comment by chylex** [comment]
As I said on the original post,

> Taking a break from this project, you can use the advanced guide to patch any version until I come back to it.
