### ISSUE TITLE
Origin OS Version Bypass - Advanced Patching Guide

### ISSUE THREAD

**Issue by chylex** [chylex/Blog#2]

**Comment by p601** [comment]
Hello, i would like to know if this guide is working or not ?

**Comment by chrp90** [comment]
Hey there! 
I can follow the instructions for the OriginClient.dll and OriginClientService.exe

However @ Origin.exe
Part 1

"A little further below, click the if in if (cVar4 == '\0') {, and patch JNZ LAB_... to JMP (e9 ** ** ** **), then patch ?? 00h to NOP (90)."

I can't locate any "if (cVar4 == '\0')" in the whole Decompile Panel only many cVar2's and cVar3's :X

Origin Version is 10.5.90.45798 - 766694

**Comment by chrp90** [comment]
To add to that 1 thing I forgot, when doing
"In the Decompile panel, click the if in if (cVar3 == '\0') { right above the found text, and patch JNZ LAB_... to JMP (eb **)."

the value above the "found text" is actually "if (cVar2 == '\0')" not cVar3

:/

**Comment by chylex** [comment]
It's possible that EA changed that part so it no longer matches, I can take a look later but I'll be busy during the holiday weeks.

**Comment by chrp90** [comment]
@chylex 
I ran through it again and even tough I still found those different values, I just went through with it and it seems to have worked! (I also noticed that I didn't uncheck PDB for the Analysation the first time whoops)

As of rn Origin is updating my Win10 only game :-)

So Thank You for this Guide, enjoy the holidays and stay tuned for my coffee :)

**Comment by onimusha-shin** [comment]
hi chrp90, i have the same Origin version as you do and ran through the instructions like you did. however, i still can't bypass the Win10 requirement for a certain game. you're saying that you managed to bypass the Win10 requirement for an installation/update?

**Comment by chrp90** [comment]
@onimusha-shin
Hey there,
Yes it worked for me!

Here are my fixed files:
https://www.file-upload.net/download-14423028/OriginVersion10.5.90.45798-766694OSBypassfixedfiles.rar.html

**Comment by xavio86** [comment]
Unfortunately doesn't work any longer (20.10.2021)
Code has changed for Origin.exe and it is impossible to replicate instructions. :(

**Comment by DarthAkuryo** [comment]
Could it be possible to update this guide? As other users have already pointed out, it's not up to date and with recent versions of Origin the above steps don't work anymore.
